lannguage: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t omkarpatil16/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true omkarpatil16/docker-react npm run test